### ISSUE TITLE
In Net6 wpf ,always has System.AccessViolationException

### ISSUE THREAD

**Issue by BianYuan1995** [mveril/MobileDeviceSharp#2]
![image](https://user-images.githubusercontent.com/20554384/196625580-9918e190-d69f-4996-88d2-56e680576abf.png)

**Comment by BianYuan1995** [comment]
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

**Comment by BianYuan1995** [comment]
I found the problem, LockdownSession session = new(device, "K-Check", true); WithHandlShare was true.

**Comment by mveril** [comment]
Hello happy to see you again ! Can you share with me a sample code showing when the error occurs or does not occur. Maybe this error is when we try to dispose a already disposed (or not initialized) handle. I am not able to determine if it's an error is in my code (the library) or on your code (the app).

**Comment by BianYuan1995** [comment]
` public async Task<DeviceModel> GetDeviceModelAsync(IDevice device)
        {
            DeviceModel model = new();
            LockdownSession session = new(device, "K-Check", false);
            try
            {

                if (!device.IsPaired)
                {
                    bool IsSuccess = await session.PairAsync();
                    if (IsSuccess)
                    {

                    }
                }
                model.SerialNumber = device.SerialNumber;
                
                //销售型号  MRRT2LL/A  ModelNumber +RegionInfo
                var ModelNumber = (PlistString)session.GetDomain()["ModelNumber"];
                var RegionInfo= (PlistString)session.GetDomain()["RegionInfo"];
                var MLBSerialNumber = (PlistString)session.GetDomain()["MLBSerialNumber"];
                model.SaleModel = ModelNumber.Value+" "+RegionInfo.Value;
                model.MLBSerialNumber= MLBSerialNumber.Value;
                var MEID = (PlistString)session.GetDomain()["MobileEquipmentIdentifier"];
                var IMEI=(PlistString)session.GetDomain()["InternationalMobileEquipmentIdentity"];
                
                if (IMEI.Value==null)
                {
                    model.DeviceIMEI=model.DeviceMEID = MEID.Value;
                }
                else
                {
                    model.DeviceIMEI = IMEI.Value;
                    model.DeviceMEID = MEID.Value;
                }
                var TimeIntervalSince1970= (PlistReal)session.GetDomain()["TimeIntervalSince1970"];
                var date = (new DateTime(1970, 1, 1)).AddMilliseconds(TimeIntervalSince1970.Value);
                var CPID = (PlistInteger)session.GetDomain()["UniqueChipID"];
                model.DeviceIECID = string.Format("{0:X}", CPID.Value);
                
                model.ProductionDate = date.ToString();
                
              
                return model;
            }
            catch(Exception ex)
            {
                return null;
            }
            finally
            {

                session.Close();
            }
        }`

**Comment by BianYuan1995** [comment]
This version above does not throw an exception, but when I add other properties to my piece of code, such as：
`ulong Capacity= device.Capacity;
  model.DeviceCapacity = FormatBytes(Capacity);
   model.DeviceVersion = device.OSVersion.ToString();
   model.SerialNumber = device.SerialNumber;
  model.ModelName = device.ModelDisplayName;`
In this case, there is always an exception

**Comment by BianYuan1995** [comment]
From IOSHandleWrapperBase  Exception
![image](https://user-images.githubusercontent.com/20554384/198529251-5b82cf3f-ff4c-4f5e-90d8-a9ec7b68a286.png)

**Comment by BianYuan1995** [comment]
/// <summary>
        /// 通过idevicediagnostics.exe
        /// </summary>
        /// <param name="device"></param>
        /// <returns></returns>
        public async Task<DeviceModel> GetDeviceInfoAsync(IDevice device)
        {
            DeviceModel model = new();
            PlistDictionary dic;
            LockdownSession session = new(device, "K", true);
            if (!device.IsPaired)
            {
                bool IsSuccess = await session.PairAsync();
                if (IsSuccess)
                {

                }
            }
            string[] args = new string[]
            {
                "ProductType",
                "ModelNumber",
                "RegionInfo",
                "MLBSerialNumber",
                "DeviceColor",
                "ProductName",
                "ProductVersion",
                "BuildVersion",
                "DeviceName",
                "MobileEquipmentIdentifier",
                "InternationalMobileEquipmentIdentity",
                "UniqueChipID"
            };
            var relay = new MobileDeviceSharp.DiagnosticsRelay.DiagnosticsRelaySession(device);
            dic = relay.QueryMobilegestalt(args);
            var ProductType = (PlistString)dic["ProductType"];//ProductType: iPhone10,1
            var ModelNumber = (PlistString)dic["ModelNumber"];//ModelNumber: MRRT2
            var RegionInfo = (PlistString)dic["RegionInfo"];//ModelNumber: MRRT2
            var MLBSerialNumber = (PlistString)dic["MLBSerialNumber"];//RegionInfo: LL/A
            var Color = (PlistString)dic["DeviceColor"];//DeviceColor: 1
            //var ProductName = (PlistString)dic["ProductName"];//ProductName: iPhone OS
            var ProductVersion = (PlistString)dic["ProductVersion"];//ProductVersion: 14.3
            var BuildVersion = (PlistString)dic["BuildVersion"];//BuildVersion: 18C66
            var DeviceName = (PlistString)dic["DeviceName"];//DeviceName: iPhone
            var buildNumber = BuildNumber.Parse(BuildVersion.Value);
            model.OsVersion = new Models.OSVersion(DeviceName.Value, Version.Parse(ProductVersion.Value), buildNumber);
            model.DeviceVersion = model.OsVersion.ToString();
            if (AppleDevices.DevicesIphones.TryGetValue(ProductType.Value, out var name))
            {
                model.ModelName = name;
            }
            if (AppleDevices.DeviceIphoneColors.TryGetValue(Color.Value, out var deviceColor))
            {
                model.DeviceColor = deviceColor;
            }
            model.SaleModel = ModelNumber.Value + " " + RegionInfo.Value;
            model.MLBSerialNumber = MLBSerialNumber.Value;
            var MEID = (PlistString)dic["MobileEquipmentIdentifier"];
            var IMEI = (PlistString)dic["InternationalMobileEquipmentIdentity"];

            if (IMEI.Value == null)
            {
                model.DeviceIMEI = model.DeviceMEID = MEID.Value;
            }
            else
            {
                model.DeviceIMEI = IMEI.Value;
                model.DeviceMEID = MEID.Value;
            }
            
            var CPID = (PlistInteger)dic["UniqueChipID"];
            model.DeviceIECID = string.Format("{0:X}", CPID.Value);
            //RegulatoryModelNumber
            return model;
        }

**Comment by BianYuan1995** [comment]
I tried to use the above method and it still raises an exception too, which occurs in the PlistHandle
![image](https://user-images.githubusercontent.com/20554384/199666475-fd87e0bd-d0b0-454f-8797-784730736abb.png)

**Comment by mveril** [comment]
Hello thank you for sharing all the infos. I currently work on `InstallationProxy` support. I will push the first commit when it will be ready and after I will switch to the master branch to work on your issue. The default value for the `withHandShake` parameter should be logically equal to `Device.IsPaired`. This is not the case today (it's currently `false`) but that doesn't explain everything. firstly I need to change the default value and after I need to investigate it.

**Comment by BianYuan1995** [comment]
Looking forward to your subsequent updates, in the later test, I think it is not the problem withHandShake parameters, I saw in debug mode, the code execution to dic = relay.QueryMobilegestalt(args);  PlistHandle.ReleaseHandle() to IOSHandleWrapperBase.Dispose() twice inside the internal assembly, and by the end of my code, there were several more PlistHandle. ReleaseHandle() raises this exception

**Comment by mveril** [comment]
> Looking forward to your subsequent updates, in the later test, I think it is not the problem withHandShake parameters, I saw in debug mode, the code execution to dic = relay.QueryMobilegestalt(args); PlistHandle.ReleaseHandle() to IOSHandleWrapperBase.Dispose() twice inside the internal assembly, and by the end of my code, there were several more PlistHandle. ReleaseHandle() raises this exception

So the problem seems to come from the `DiagnosticsRelaySession.QueryMobilegestalt` API
I also use it two time in my own code for: https://github.com/mveril/MobileDeviceSharp/blob/852f2e1af68d5732f833e1838114d21834ecfaf7/src/MobileDeviceSharp/OSVersion.cs#L13
and https://github.com/mveril/MobileDeviceSharp/blob/852f2e1af68d5732f833e1838114d21834ecfaf7/src/MobileDeviceSharp/IDevice.cs#L187 and I also observed an exception when I use it with an unpared device (but this is not the case for you).  I hope I will have time to investigate it during this week-end.

**Comment by BianYuan1995** [comment]
Looking forward to your update can be solved

**Comment by mveril** [comment]
I succeed in reproduce your bug I don't realy know where it come from. On my side your code throws a LockdownException because `MobileEquipmentIdentifier` does not exist on my iPhone (an iPhone 14 with iOS 16.1 with Orange France as phone operator) Be careful about that (maybe I will be wrap it in a KeyNotFoundException) . So, I commented this part and I finally got the 
`AccessViolationException`. I will search why this week-end.

**Comment by mveril** [comment]
Hello @BianYuan1995
In my [previous message](https://github.com/mveril/MobileDeviceSharp/issues/2#issuecomment-1310001505) I totally were wrong.
Unlike my code, your code does not use `Dispose()` on variables of type `PlistNode`.  So when the garbage collector collects the `PlistNode` the finalizer is called.. It's also true for the `PlistHandle` finalizer. It seems that calling the two finalizer causes the unmanaged memory to be cleaned twice and cause the `AccessViolationException` (the joys of C/C# interoperability). The solution was given to me by this [blog post](https://blog.benoitblanchon.fr/safehandle) by @bblanchon (thanks to him). According to his blog post:
>The only thing I really had to implement is the `ReleaseHandle()` methods. It will be called by `SafeHandle` finalizer and `Dispose()`.
>
>Then, you can use the `SafeHandle` **as a managed resource**:

The important words here is "as a managed resource" because if the `SafeHandle` is a managed resource we need to dispose it only when the `Dispose()` method is called and not in the finalizer. So I applied this fix on the commit f91bad4. Normally this issue is solved. It's work on my side but I'm waiting for your feedback to close it. Thank you to report this issue. Maybe I will also integrate some of the value you used in as property for the `IDevice` class.

**Comment by BianYuan1995** [comment]
Hello @mveril , thank you for you update. but  use last update ,i still found same issues  .when i use DiagnosticsRelaySession , Whether or not use Dispose() ,so Now I don't know what is the right way to operate

**Comment by BianYuan1995** [comment]
![image](https://user-images.githubusercontent.com/20554384/202983843-44766c4d-41ba-43d4-ac43-0bbbbfafd8e4.png)
this is not use Dispose() .The result Query ended unexpectedly. in my program . The program flashes unexpectedly.Event viewer with error events.
![image](https://user-images.githubusercontent.com/20554384/202984494-492116ac-8bbf-45cd-8074-39c702bd0693.png)
when use Dispose() or Close()
![image](https://user-images.githubusercontent.com/20554384/202984682-1061a3ad-b581-4488-b0ed-088bfee99c63.png)

**Comment by BianYuan1995** [comment]
Also using DiagnosticsRelaySession, but using the method QueryIoregistryEntry is possible and does not cause an exception

**Comment by mveril** [comment]
Hello @BianYuan1995.
If I understand correctly what you said the problem is now only on `QueryMobilegestalt`, not in PlistNode in general ? 
For this API I manipulated a lot `PlistNodes` with `using` (so implicitly `Dispose()`) and `Clone()`. It's maybe the source of this specific issue. I will investigate it this week-end.
Are you try the different overloads of this API ? There are currently 3:
https://github.com/mveril/MobileDeviceSharp/blob/ee0b355b192ec62f70c63e70feda3cf17b5da3dd/src/MobileDeviceSharp/DiagnosticsRelay/DiagnosticsRelaySessionBase.cs#L56
https://github.com/mveril/MobileDeviceSharp/blob/ee0b355b192ec62f70c63e70feda3cf17b5da3dd/src/MobileDeviceSharp/DiagnosticsRelay/DiagnosticsRelaySessionBase.cs#L69
and internally, the previous two call the lower level:
https://github.com/mveril/MobileDeviceSharp/blob/ee0b355b192ec62f70c63e70feda3cf17b5da3dd/src/MobileDeviceSharp/DiagnosticsRelay/DiagnosticsRelaySessionBase.cs#L75
Maybe the different overloads will allow you to work around the problem temporarily and also allow you to give me some clues to see if the problem is on this
https://github.com/mveril/MobileDeviceSharp/blob/ee0b355b192ec62f70c63e70feda3cf17b5da3dd/src/MobileDeviceSharp/DiagnosticsRelay/DiagnosticsRelaySessionBase.cs#L75
or only on this
https://github.com/mveril/MobileDeviceSharp/blob/ee0b355b192ec62f70c63e70feda3cf17b5da3dd/src/MobileDeviceSharp/DiagnosticsRelay/DiagnosticsRelaySessionBase.cs#L56

**Comment by BianYuan1995** [comment]
Hello @mveril 
Right, I tried the three overloaded methods of QueryMobilegestalt and all have the same exception

**Comment by mveril** [comment]
Hello @BianYuan1995 
I fixed another thing in `PlistHandle` by modifying my `HandleGenerator`
Indeed, if we read the [C++ code of the destructor of Node of the libplist library](https://github.com/libimobiledevice/libplist/blob/307fcc5f95f06ecd6fb7e3769450a923b8aaba26/src/Node.cpp#L89-L99) we see that we mustn't release a handle of a `PlistNode` that have a parent
So, I fixed that and now the generated code for the `PlistHandle` is like this
```csharp
protected override bool ReleaseHandle()
{
    if (CanBeReleased())
    {
        Plist.plist_free(this.handle);
    }
    return true;
}
```
And for `PlistHandle` the `CanBeReleased()` method is defined here 
https://github.com/mveril/MobileDeviceSharp/blob/3de6b05411762887c4174b9b25f29fb584c08e10/src/MobileDeviceSharp/PropertyList/Native/PlistHandle.cs#L10-L13
So now only root nodes will be released, like it should be.
I think that can fix your bug.

**Comment by mveril** [comment]
Ok there is an issue with my new code I need to fix it before.

**Comment by BianYuan1995** [comment]
![image](https://user-images.githubusercontent.com/20554384/204420318-21b3f5d8-2b87-48e2-896b-257c38470ffe.png)

**Comment by BianYuan1995** [comment]
Hello @mveril .This update causes an exception to occur when the previously available LockdownSession obtains device information, usually triggered some time after the end of the code

**Comment by BianYuan1995** [comment]
my code:
![image](https://user-images.githubusercontent.com/20554384/204422978-a2d24692-d9e3-46d9-a085-6e5caeeadd62.png)

**Comment by BianYuan1995** [comment]
I seem to have found the problem, I tried at the end of the method defaultDomain=null, and it worked fine

**Comment by mveril** [comment]
Hello @BianYuan1995
Is the issue with `DiagnosticsRelaySession`  of your [previous message](https://github.com/mveril/MobileDeviceSharp/issues/2#issuecomment-1321541318) fixed ? Normally the code of your last message is perfectly correct and If my memory is good look like what I did for the properties of the `IDevice` class.
You said an interesting thing.
>  usually triggered some time after the end of the code

Sounds like another finalizer problem to me (for me the finalizer is call even if the Node is already disposed maybe by the unmanaged code). I definitively need to fix that kind of issue. Maybe I will have some time to check it this week end. Thank you for your patience despite the persistence of this issue.

**Comment by BianYuan1995** [comment]
Hello @mveril 
I tested DiagnosticsRelaySession and it seems that the problem is solved, but if you add Thread.sleep(5000) after the test code, it also raises an exception during the session

**Comment by BianYuan1995** [comment]
Provide some information, such as the above image code, I have some old code, the use of LockdownSession , used to query the device information, he was in the previous update, after a lot of testing, is feasible, of course, there are occasional exceptions resulting in flashbacks. But after this update, his abnormal flashback seems to be inevitable, all occurring some time after the completion of the execution, and I was able to reproduce successfully in the test code through Thread.sleep(5000)

**Comment by mveril** [comment]
Hello @BianYuan1995
I think I solved the issue now in the commit  b863b20. Like I explain last time, if `PlistNode` has parent, the parent must be responsible to release it. I solve the issue using a [custom marshaler](https://github.com/mveril/MobileDeviceSharp/blob/b863b208a18f89990d32731501a35fe1a0b74cb2/src/MobileDeviceSharp/PropertyList/Native/PlistHandleNotOwnedMarshaller.cs). `SafeHandleZeroOrMinusOneIsInvalid` [constructor](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.safehandles.safehandlezeroorminusoneisinvalid.-ctor#microsoft-win32-safehandles-safehandlezeroorminusoneisinvalid-ctor(system-boolean)) has the `ownsHandle` parameter to determine if the handle must be release when it's garbage collected. By default, I set it to `true` which say to release the handle at the end. But this behavior is not always good for PlistHandle. So when I want to create a `PlistHandle` which must not release the handle I apply my custom marshaller which create the `PlistHandle` with the `ownHandle` parameter seres to `false`. I think this solve the issue. When I tested, I used a `Task.Delay` with a long time to give a suffisent time to the garbage collector to do its work. But as always, I wait your feedback to be sure your issue is completely solved.
Thank you for your patience.

**Comment by mveril** [comment]
The trick I used [previously](https://github.com/mveril/MobileDeviceSharp/issues/2#issuecomment-1328230591) to try to solve your issue is definitively bad so in the commit of my new fix (b863b20) I also reverted all the commits related to it.

**Comment by mveril** [comment]
Hello @BianYuan1995
I have no answer from you since the fix I apply in b863b20.
I also applied a fix for `PlistDictionary` in 00c9ac4 to fix some issues when we try retrieve a value from a key which is not present in the dictionary.
Is your issue fixed ?

**Comment by BianYuan1995** [comment]
Hello @mveril
Sorry for replying now, I've been a bit busy lately, I think it should be fixed, I used the last update and the problem didn't reappear, so I think your fix is working.

**Comment by BianYuan1995** [comment]
00c9ac4 update , I have not applied yet, I will try to pull the update soon, thanks again for your reply and update

**Comment by BianYuan1995** [comment]
I used the latest update 00c9ac4 and no problems occurred, so I think I can close this issue now

**Comment by mveril** [comment]
Thank you a lot for your feedback!
This issue was very complicated to debug.
Now I try to implement [Installation Proxy](https://docs.libimobiledevice.org/libimobiledevice/latest/installation__proxy_8h.html) and [House Arrest](https://docs.libimobiledevice.org/libimobiledevice/latest/house__arrest_8h.html) but these are currently too buggy to be included on the main branch I added a branch for each of it (also my implementation of house arrest depends on installation proxy).
Feel free to come back to me for any bug or any suggestion, or if you want to contribute more on the project.
